Use highway simd for SquaredL2 calculation
google/gemma.cpp pull request #77
Opened 2024-03-05 09:40 UTC by enum-class

use highway for SquaredL2 calculation.

2024-03-05 11:35 UTC, jan-wassenberg requested changes
Nice, thanks for vectorizing :)

2024-03-05 11:35 UTC, jan-wassenberg commented on ops.h
> +  HWY_DASSERT(size >= N);
Let's check `>= 2*N`, the loop step size.

2024-03-05 11:35 UTC, jan-wassenberg commented on ops.h
> +  for (size_t i = 0; i + 2 * N <= size; i += 2 * N) {
I used to like this loop structure but GCC raises static analysis warnings about it due to overflow if (theoretically) `i` gets huge.
The safer alternative is to check `if (size >= 2*N)` (or assert, as you are already doing), then `for (i = 0; i <= size - 2*N; i += 2*N)`. Does that make sense?

2024-03-06 02:04 UTC, jan-wassenberg approved these changes
Thanks for making the change!

2024-03-08 01:50 UTC, enum-class commented
Same issue with copybara here, I think it needs a restart too:)

2024-03-11 04:08 UTC, austinvhuang commented
Since https://github.com/google/gemma.cpp/pull/78 was merged this may need to merge the updated `dev` into this branch to be able to finalize the merge. May take a stab tomorrow if nobody else gets to it.

2024-03-11 13:26 UTC, merged

2024-03-11 13:31 UTC, austinvhuang commented
Thanks, merged now!